<?
$arTooltips = array(

	"THUMBS_POSITION" => GetMessage("THUMBS_POSITION_TIP"),
	"SHOW_DETAIL_PICTURE" => GetMessage("SHOW_DETAIL_PICTURE_TIP"),
	"NAME_PHOTO" => GetMessage("NAME_PHOTO_TIP"),
	"DONT_CUT_MINI" => GetMessage("DONT_CUT_MINI_TIP"),
	"PREVIEW_HEIGHT" => GetMessage("PREVIEW_HEIGHT_TIP"),
	"PREVIEW_WIDTH" => GetMessage("PREVIEW_WIDTH_TIP"),
	"INTERVAL" => GetMessage("INTERVAL_TIP"),
	
);
?>